#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Auto-generate GALLERY.md from every styles/<slug>/STYLE.md.

The style packs are the single source of truth. Run this after adding/editing a
pack; CI also runs `--check` to fail a PR whose pack is malformed.

自动从每个 styles/<slug>/STYLE.md 生成 GALLERY.md。风格包是单一事实源。
"""
import os, re, sys, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
REQUIRED = ["name", "slug", "medium", "author", "license", "prompt_formula", "samples"]


def parse_front(path):
    s = open(path, encoding="utf-8").read()
    m = re.match(r"^---\n(.*?)\n---", s, re.S)
    if not m:
        return None, "no frontmatter"
    fm, d, key = m.group(1), {}, None
    for ln in fm.split("\n"):
        if ln.strip().startswith("#") or not ln.strip():
            continue
        mm = re.match(r"^([a-z_]+):\s?(.*)$", ln)
        if mm:
            key = mm.group(1)
            d[key] = mm.group(2).strip().strip(chr(34))
        elif key == "samples" and ln.strip().startswith("- "):
            d.setdefault("_samples", []).append(ln.strip()[2:].strip())
        elif key == "prompt_formula" and (ln.startswith("  ") or ln.startswith("\t")):
            d["prompt_formula"] = (d.get("prompt_formula", "") + "\n" + ln.strip()).strip()
    if "_samples" in d:
        d["samples"] = d["_samples"]
    elif d.get("samples"):
        d["samples"] = [d["samples"]]
    return d, None


def validate(pack_dir):
    style = os.path.join(pack_dir, "STYLE.md")
    if not os.path.exists(style):
        return ["missing STYLE.md"]
    d, err = parse_front(style)
    if err:
        return [err]
    problems = []
    for k in REQUIRED:
        if not d.get(k):
            problems.append("missing field: " + k)
    slug = os.path.basename(pack_dir.rstrip("/"))
    if d.get("slug") and d["slug"] != slug:
        problems.append("slug '%s' != folder '%s'" % (d.get("slug"), slug))
    for s in (d.get("samples") or []):
        if not os.path.exists(os.path.join(pack_dir, s)):
            problems.append("sample not found: " + s)
    return problems


def build():
    packs = []
    for style in sorted(glob.glob(os.path.join(ROOT, "styles", "*", "STYLE.md"))):
        pd = os.path.dirname(style)
        if os.path.basename(pd) == "_template":
            continue
        d, err = parse_front(style)
        if err:
            continue
        d["_dir"] = "styles/" + os.path.basename(pd)
        packs.append(d)
    by_medium = {}
    for p in packs:
        by_medium.setdefault(p.get("medium", "Other"), []).append(p)
    out = ["# Gallery\n",
           "> Auto-generated by `build_gallery.py` from the style packs — don't edit by hand.\n",
           "> Each style ships one reproducible prompt formula. Add your own: copy `styles/_template/` and open a PR (see CONTRIBUTING).\n"]
    for medium in sorted(by_medium):
        out.append("\n## %s\n" % medium)
        for p in by_medium[medium]:
            hand = (" · %s" % p["hand"]) if p.get("hand") else ""
            out.append("### %s%s\n" % (p.get("name"), hand))
            for s in (p.get("samples") or [])[:2]:
                out.append("![%s](%s/%s)\n" % (p.get("name"), p["_dir"], s))
            out.append("Medium **%s**%s · [pack & prompt formula →](%s/STYLE.md)\n"
                       % (p.get("medium"), (" · hand **%s**" % p["hand"]) if p.get("hand") else "", p["_dir"]))
    open(os.path.join(ROOT, "GALLERY.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
    # machine-readable manifest so agents can resolve a named style -> pack + formula
    import json as _json
    # Chinese aliases so zh style names resolve deterministically (not just via LLM knowledge)
    ALIAS_ZH = {
        "ink-wash": ["水墨", "水墨画"], "founding-charter": ["独立宣言", "建国文书", "羊皮纸契约", "契约"], "kintsugi": ["金继", "金缮"], "stele-rubbing": ["拓片", "碑拓"],
        "portolan": ["航海图", "海图"], "davinci-copperplate": ["达芬奇铜版", "达芬奇"],
        "swiss-grid": ["瑞士网格", "瑞士极简"], "blue-white-porcelain": ["青花", "青花瓷"],
        "porcelain-indigo": ["瓷白靛青"], "warm-sepia": ["暖棕手绘", "铅笔手绘"],
        "dunhuang-mural": ["敦煌", "敦煌壁画"], "ukiyoe-woodblock": ["浮世绘"],
        "cyanotype-botanical": ["氰版", "蓝晒"], "papercraft": ["纸雕", "纸艺"],
        "clay-3d": ["粘土", "黏土"], "artdeco-gold": ["装饰艺术", "黑金"],
        "celestial-gold": ["深空鎏金", "星图"], "batik-waxresist": ["蜡染"],
        "shu-brocade": ["蜀锦"], "kesi-tapestry": ["缂丝"], "cloisonne": ["景泰蓝"],
        "lacquer-mop-inlay": ["漆器螺钿", "螺钿"], "zellige-girih": ["摩洛哥瓷砖"],
        "kente-cloth": ["肯特布"], "bogolanfini-mudcloth": ["泥布"],
        "cinema-nolan": ["诺兰"], "cinema-villeneuve": ["维伦纽瓦"],
        "cinema-wongkarwai": ["王家卫"], "cinema-wesanderson": ["韦斯安德森", "韦斯·安德森"],
        "cinema-kubrick": ["库布里克"], "cinema-zhangyimou": ["张艺谋"],
        "cinema-fincher": ["芬奇"], "cinema-tarkovsky": ["塔可夫斯基"],
        "cinema-hou-koreeda": ["侯孝贤", "是枝裕和"], "cinema-hitchcock": ["希区柯克"],
        "cinema-kurosawa": ["黑泽明"], "swiss- grid": [],
        "embroidery-tapestry": ["刺绣"], "stone-relief": ["石雕", "浮雕"],
        "leather-gilt": ["皮革烫金"], "broadsheet-news": ["凸版报纸", "铅字报纸"],
        "screenprint-poster": ["丝网印刷", "丝网"], "enamel-signage": ["搪瓷"],
        "watercolor-editorial": ["水彩"], "cyber-blueprint": ["赛博蓝图", "蓝图线框"],
        "retro-science-cutaway": ["复古科普"],
    }
    manifest = []
    for p in packs:
        pf = p.get("prompt_formula", "")
        if pf[:1] in ("|", ">"):
            pf = pf[1:].strip()
        p = dict(p, prompt_formula=pf)
        manifest.append({
            "slug": p.get("slug"),
            "name": p.get("name"),
            "medium": p.get("medium"),
            "hand": p.get("hand", ""),
            "tags": [t for t in re.findall(r"[\w-]+", p.get("tags", ""))],
            "aliases": [p.get("name", ""), p.get("slug", "").replace("-", " ")] + ALIAS_ZH.get(p.get("slug", ""), []),
            "pack": p.get("_dir"),
            "prompt_formula": p.get("prompt_formula", ""),
            "license": p.get("license", "CC-BY-4.0"),
        })
    open(os.path.join(ROOT, "styles.json"), "w", encoding="utf-8").write(
        _json.dumps({"skill": "ppt-zen", "styles": manifest}, ensure_ascii=False, indent=1))
    print("styles.json: %d styles" % len(manifest))
    return len(packs)


if __name__ == "__main__":
    if "--check" in sys.argv:
        bad = 0
        for style in glob.glob(os.path.join(ROOT, "styles", "*", "STYLE.md")):
            pd = os.path.dirname(style)
            if os.path.basename(pd) == "_template":
                continue
            probs = validate(pd)
            if probs:
                bad += 1
                print("FAIL %s: %s" % (os.path.basename(pd), "; ".join(probs)))
        if bad:
            sys.exit("%d style pack(s) invalid" % bad)
        print("all style packs valid")
    else:
        n = build()
        print("GALLERY.md rebuilt from %d style pack(s)" % n)
